spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_account
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
